name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
      - pre-prod


jobs:
  terraform:
    runs-on: ubuntu-latest    
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Terraform Init
        working-directory: ../../environments/pre-prod
        run: terraform init

      - name: Terraform Format
        working-directory: ../../environments/pre-prod
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ../../environments/pre-prod
        run: terraform validate

      - name: Terraform Plan
        working-directory: ../../environments/pre-prod
        run: terraform plan

      - name: Terraform Apply (pre-prod)
        working-directory: ../../environments/pre-prod
        run: terraform apply
