name: Terraform CI/CD

on:
  push:
    branches:
      - pre-prod


jobs:
  
  terraform:
    name: Terraform
    runs-on: self-hosted
    environment: 
      name: ${{ github.ref_name }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Terraform Init
        run: terraform init -backend-config=environments/${{ github.ref_name }}/backend.conf

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=environments/${{ github.ref_name }}/terraform.tfvars

      - name: Terraform Apply (pre-prod)
        if: github.ref == 'refs/heads/pre-prod'
        run: terraform apply -var-file=environments/${{ github.ref_name }}/terraform.tfvars
