name: Terraform CI/CD

on:
  push:
    branches:
      - pre-prod
      - prod

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -backend-config=envs/${{ github.ref_name }}/backend.hcl
        working-directory: envs/${{ github.ref_name }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: envs/${{ github.ref_name }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: envs/${{ github.ref_name }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: envs/${{ github.ref_name }}